
INSERT INTO public.portfolio_projects (title, slug, category, description, technologies, is_published, sort_order, alt_text) VALUES
('Company Formation — UK & UAE','consultancy-company-formation','Consultancy','End-to-end company incorporation across UK and UAE jurisdictions including trade name reservation, MOA drafting, and bank account setup.', ARRAY['Incorporation','Compliance','UK','UAE']::text[], true, 201, 'Company formation consultancy project — UK and UAE incorporation services'),
('Business Consultancy Retainer','consultancy-business-consultancy-retainer','Consultancy','Monthly strategic advisory engagement covering operations, hiring, vendor management and KPI tracking for a B2B SaaS founder.', ARRAY['Strategy','Operations','KPIs']::text[], true, 202, 'Business consultancy retainer project — strategic advisory and operations'),
('Business Banking Advice','consultancy-business-banking-advice','Consultancy','Multi-currency business banking selection, merchant account onboarding, and FX cost optimisation for an e-commerce exporter.', ARRAY['Banking','Fintech','Payments']::text[], true, 203, 'Business banking advisory project — multi-currency accounts and merchant onboarding'),
('Tax & VAT Advisory','consultancy-tax-vat-advisory','Consultancy','VAT registration, return filing and corporate tax planning for SMEs operating across GCC and EU markets.', ARRAY['Tax','VAT','Compliance']::text[], true, 204, 'Tax and VAT advisory consultancy — registration, filing and planning'),
('Business Strategy & GTM','consultancy-business-strategy-gtm','Consultancy','Market entry analysis, ICP definition and 12-month go-to-market roadmap for an early-stage fintech startup.', ARRAY['Strategy','GTM','Market Entry']::text[], true, 205, 'Business strategy and go-to-market consultancy project'),
('Trade License & Compliance','consultancy-trade-license-compliance','Consultancy','Mainland and free-zone trade licensing, activity selection, PRO services and annual compliance renewals.', ARRAY['Licensing','PRO','Compliance']::text[], true, 206, 'Trade license and compliance advisory project'),
('Investor Pitch Advisory','consultancy-investor-pitch-advisory','Consultancy','Investor deck refinement, financial model review and pre-seed fundraise coaching for a D2C brand.', ARRAY['Fundraising','Pitch Deck','Financial Model']::text[], true, 207, 'Investor pitch advisory consultancy project'),
('Bookkeeping & Accounts','consultancy-bookkeeping-accounts','Consultancy','Cloud bookkeeping setup on Xero and QuickBooks with monthly close, payroll and management reporting.', ARRAY['Xero','QuickBooks','Payroll']::text[], true, 208, 'Bookkeeping and accounting consultancy project'),

('SEO Growth Campaign','marketing-seo-growth-campaign','Marketing','6-month technical SEO + content programme that grew organic traffic 312% and lifted commercial keyword rankings.', ARRAY['SEO','Content','Technical SEO']::text[], true, 301, 'SEO growth marketing project — organic traffic and ranking improvements'),
('Google Ads — Lead Generation','marketing-google-ads-lead-gen','Marketing','High-intent search and PMax campaigns for B2B lead generation, reducing CPL by 47% with conversion-tracked landing pages.', ARRAY['Google Ads','PMax','Landing Pages']::text[], true, 302, 'Google Ads lead generation marketing campaign project'),
('Meta Ads — E-commerce Scaling','marketing-meta-ads-ecommerce','Marketing','Full-funnel Facebook and Instagram ad strategy with creative testing framework that scaled ROAS from 1.8 to 4.2.', ARRAY['Meta Ads','Facebook','Instagram']::text[], true, 303, 'Meta Ads e-commerce scaling marketing project'),
('Brand Identity & Guidelines','marketing-brand-identity-guidelines','Marketing','Complete brand system — logo, typography, color, voice and usage guidelines for a hospitality startup.', ARRAY['Branding','Logo','Guidelines']::text[], true, 304, 'Brand identity and guidelines marketing project'),
('Social Media Management','marketing-social-media-management','Marketing','Always-on content calendar, community management and short-form video production across IG, TikTok and LinkedIn.', ARRAY['Social Media','Content','Short-form Video']::text[], true, 305, 'Social media management marketing project'),
('Content Marketing Engine','marketing-content-marketing-engine','Marketing','Editorial strategy, SEO briefs, and weekly publishing workflow producing 40+ ranked articles per quarter.', ARRAY['Content','Editorial','SEO']::text[], true, 306, 'Content marketing engine project — editorial strategy and publishing'),
('Email & Lifecycle Marketing','marketing-email-lifecycle','Marketing','Klaviyo lifecycle flows, segmentation and weekly campaigns that contributed 28% of total store revenue.', ARRAY['Email','Klaviyo','Lifecycle']::text[], true, 307, 'Email and lifecycle marketing project — automated flows and campaigns'),
('E-commerce Growth Sprint','marketing-ecommerce-growth-sprint','Marketing','12-week growth sprint combining CRO audit, paid social, influencer partnerships and email automation.', ARRAY['CRO','Paid Social','Influencer','Email']::text[], true, 308, 'E-commerce growth sprint marketing project');
