// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://isweduliawwjqwhyvwhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlzd2VkdWxpYXd3anF3aHl2d2hwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcwMzU2NTIsImV4cCI6MjA5MjYxMTY1Mn0.I7InCnynzCOzjZPi_IOb3L9pVUJ7YgebDNWuNb6Uu9M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});